name: Post Emily Dickinson Poem

on:
  schedule:
    - cron: '* 11 * * *'  # runs every day at 11:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atproto requests python-dotenv

      - name: Run bot
        env:
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python embot.py

      - name: Log timestamp
        run: echo "Scheduled job ran at $(date -u)"

